update aicoeci base image
thoth-station/integration-tests pull request #282
Opened 2022-03-08 13:28 UTC by goern

- added some test cases
- update AICoE-CI image version
- update pre-commit plugins
- update pyproject

2022-03-08 13:28 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **goern** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fintegration-tests).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/integration-tests/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["goern"]} -->

2022-03-08 13:31 UTC, fridex commented on features/data/project/provenance_flask_error/Pipfile
> +python_version = "3.9"
```suggestion
python_version = "3.8"
```

2022-03-08 14:34 UTC, codificat requested changes
A couple of requests for pre-commit config updates

2022-03-08 14:34 UTC, codificat commented on .pre-commit-config.yaml
> +    rev: v1.1.13
Please take the opportunity to switch from `git://` to `https://`  (ref https://github.com/thoth-station/thoth-application/issues/2111)

2022-03-08 14:34 UTC, codificat commented on .pre-commit-config.yaml
> +    rev: v4.1.0
same here (switch from `git://` to `https://`), but also there is another `pre-commit/pre-commit-hooks` section below, so better fold the hooks into that one (and remove duplicates)

2022-04-04 08:18 UTC, mayaCostantini commented
I think this PR can be closed as changes were already made by https://github.com/thoth-station/integration-tests/pull/304 and https://github.com/thoth-station/integration-tests/pull/307

2022-04-04 08:26 UTC, goern commented
/close

2022-04-04 08:26 UTC, closed without merging

2022-04-04 08:26 UTC, sesheta commented
@goern: Closed this PR.

<details>

In response to [this](https://github.com/thoth-station/integration-tests/pull/282#issuecomment-1087263987):

>/close


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>